version: 2.1

parameters:
  # This parameter is used to trigger the main workflow
  trigger:
    type: boolean
    default: true

  # A parameter per package
  log-processing:
    type: boolean
    default: false

executors:
  node:
    docker:
      - image: circleci/node:12

jobs:
  trigger-workflows:
    executor: node
    steps:
      - checkout
      - run:
          name: Trigger workflows
          command: chmod +x .circleci/circle_trigger.sh && .circleci/circle_trigger.sh

  test:
    executor: node
    parameters:
      package_path:
        type: string
    steps:
      - restore_cache:
          keys:
          - v1-dependencies-{{ checksum "<< parameters.package_path >>/package.json" }}
          - v1-dependencies-
      - run: cd << parameters.package_path >> && yarn install
      - save_cache:
          paths:
            - node_modules
          key: v1-dependencies-{{ checksum "<< parameters.package_path >>/package.json" }}
      - run: cd << parameters.package_path >> && yarn build
      - run: cd << parameters.package_path >> && yarn test

workflows:
  version: 2

  # The main workflow responsible for triggering all other workflows
  # in which changes are detected.
  ci:
    when: << pipeline.parameters.trigger >>
    jobs:
      - trigger-workflows


  # Workflows defined for each package.

  log-processing:
    when: << pipeline.parameters.log-processing >>
    jobs:
      - test:
          package_path: ./src/log-processing