version: 2.1

parameters:
  # This parameter is used to trigger the main workflow
  trigger:
    type: boolean
    default: true

  # A parameter per package
  log-processing:
    type: boolean
    default: false

  log-collector:
    type: boolean
    default: false

executors:
  node:
    docker:
      - image: circleci/node:12

  node-machine: 
    machine:
      image: default

jobs:
  trigger-workflows:
    executor: node
    steps:
      - checkout
      - run:
          name: Trigger workflows
          command: chmod +x .circleci/circle_trigger.sh && .circleci/circle_trigger.sh

  build:
    executor: node
    parameters:
      package_name:
        type: string
    working_directory: ~/project/src/<< parameters.package_name >>
    steps:
      - checkout:
          path: ~/project
      - restore_cache:
          keys:
          - v1-dependencies-{{ checksum "./package.json" }}
          - v1-dependencies-
      - run: yarn install
      - save_cache:
          paths:
            - ~/project/src/<< parameters.package_name >>/node_modules
            - ~/project/node_modules
          key: v1-dependencies-{{ checksum "./package.json" }}
      - run: yarn build
      - persist_to_workspace:
          root: ~/
          paths:
            - project

  lint:
    executor: node
    parameters:
      package_name:
        type: string
    working_directory: ~/project/src/<< parameters.package_name >>
    steps:
      - attach_workspace:
          at: ~/
      - run: yarn lint

  test:
    executor: node-machine
    parameters:
      package_name:
        type: string
    working_directory: ~/project/src/<< parameters.package_name >>
    steps:
      - attach_workspace:
          at: ~/
      - run:
          command: |
            export NVM_DIR="/opt/circleci/.nvm"
            [ -s "$NVM_DIR/nvm.sh" ] && . "$NVM_DIR/nvm.sh"
            nvm install v12.18.1 && nvm use v12.18.1 && nvm alias default v12.18.1
            npm run test
            
workflows:
  version: 2

  # The main workflow responsible for triggering all other workflows
  # in which changes are detected.
  ci:
    when: << pipeline.parameters.trigger >>
    jobs:
      - trigger-workflows


  # Workflows defined for each package.

  log-processing:
    when: << pipeline.parameters.log-processing >>
    jobs:
      - build:
          name: log-processing-build
          package_name: log-processing
      - lint:
          package_name: log-processing
          requires:
            - log-processing-build
      - test:
          package_name: log-processing
          requires:
            - log-processing-build

  log-collector:
    when: << pipeline.parameters.log-collector >>
    jobs:
      - build:
          name: log-collector-build
          package_name: log-collector
      - lint:
          package_name: log-collector
          requires:
            - log-collector-build
      - test:
          package_name: log-collector
          requires:
            - log-collector-build